trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r app/requirements.txt
  displayName: Install Dependencies

- script: |
    docker build -t flask-k8s ./app
  displayName: Build Docker Image

- script: |
    echo "Pipeline completed successfully"
  displayName: Finish
